blueprint:
  name: Moes/Tuya 4-Button Scene Switch (TS0044)
  description: >
    Controls various entities based on single and double press actions from a Moes 4-Button Scene Switch.
  domain: automation
  input:
    switch_device:
      name: Zigbee Device
      description: Select the Moes/Tuya 4-Button Scene Switch.
      selector:
        device:
          integration: zha

    single_1:
      name: Action for 1 Single Press
      description: Action to run when button 1 is single pressed.
      selector:
        action: {}
    single_2:
      name: Action for 2 Single Press
      description: Action to run when button 2 is single pressed.
      selector:
        action: {}
    single_3:
      name: Action for 3 Single Press
      description: Action to run when button 3 is single pressed.
      selector:
        action: {}
    single_4:
      name: Action for 4 Single Press
      description: Action to run when button 4 is single pressed.
      selector:
        action: {}

    double_1:
      name: Action for 1 Double Press
      description: Action to run when button 1 is double pressed.
      selector:
        action: {}
    double_2:
      name: Action for 2 Double Press
      description: Action to run when button 2 is double pressed.
      selector:
        action: {}
    double_3:
      name: Action for 3 Double Press
      description: Action to run when button 3 is double pressed.
      selector:
        action: {}
    double_4:
      name: Action for 4 Double Press
      description: Action to run when button 4 is double pressed.
      selector:
        action: {}

    hold_1:
      name: Action for 1 Hold Press
      description: Action to run when button 1 is held.
      selector:
        action: {}
    hold_2:
      name: Action for 2 Hold Press
      description: Action to run when button 2 is held.
      selector:
        action: {}
    hold_3:
      name: Action for 3 Hold Press
      description: Action to run when button 3 is held.
      selector:
        action: {}
    hold_4:
      name: Action for 4 Hold Press
      description: Action to run when button 4 is held.
      selector:
        action: {}

trigger:
  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    id: button_1_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    id: button_2_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    id: button_3_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    id: button_4_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    id: button_1_double

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    id: button_2_double

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_double_press
    subtype: button_3
    id: button_3_double

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_double_press
    subtype: button_4
    id: button_4_double

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_long_press
    subtype: button_1
    id: button_1_hold

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_long_press
    subtype: button_2
    id: button_2_hold

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_long_press
    subtype: button_3
    id: button_3_hold

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_long_press
    subtype: button_4
    id: button_4_hold

action:
  - choose:
      - conditions:
          - condition: trigger
            id: button_1_single
        sequence: !input single_1

      - conditions:
          - condition: trigger
            id: button_2_single
        sequence: !input single_2

      - conditions:
          - condition: trigger
            id: button_3_single
        sequence: !input single_3

      - conditions:
          - condition: trigger
            id: button_4_single
        sequence: !input single_4

      - conditions:
          - condition: trigger
            id: button_1_double
        sequence: !input double_1

      - conditions:
          - condition: trigger
            id: button_2_double
        sequence: !input double_2

      - conditions:
          - condition: trigger
            id: button_3_double
        sequence: !input double_3

      - conditions:
          - condition: trigger
            id: button_4_double
        sequence: !input double_4

      - conditions:
          - condition: trigger
            id: button_1_hold
        sequence: !input hold_1

      - conditions:
          - condition: trigger
            id: button_2_hold
        sequence: !input hold_2

      - conditions:
          - condition: trigger
            id: button_3_hold
        sequence: !input hold_3

      - conditions:
          - condition: trigger
            id: button_4_hold
        sequence: !input hold_4

mode: single