blueprint:
  name: Moes/Tuya 4-Button Scene Switch (TS0044)
  description: >
    Controls various entities based on single and double press actions from a Moes 4-Button Scene Switch.
  domain: automation

  input:
    switch_device:
      name: Zigbee Device
      description: Select the Moes/Tuya 4-Button Scene Switch.
      selector:
        device:
          integration: zha

    single_1:
      name: Action for 1 Single Press
      selector:
        action: {}
    single_2:
      name: Action for 2 Single Press
      selector:
        action: {}
    single_3:
      name: Action for 3 Single Press
      selector:
        action: {}
    single_4:
      name: Action for 4 Single Press
      selector:
        action: {}

    double_1:
      name: Action for 1 Double Press
      selector:
        action: {}
    double_2:
      name: Action for 2 Double Press
      selector:
        action: {}
    double_3:
      name: Action for 3 Double Press
      selector:
        action: {}
    double_4:
      name: Action for 4 Double Press
      selector:
        action: {}

    hold_1:
      name: Action for 1 Hold Press
      selector:
        action: {}
    hold_2:
      name: Action for 2 Hold Press
      selector:
        action: {}
    hold_3:
      name: Action for 3 Hold Press
      selector:
        action: {}
    hold_4:
      name: Action for 4 Hold Press
      selector:
        action: {}

trigger:
  - platform: mqtt
    topic: !input switch_topic

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_single' }}"
        sequence: !input single_1

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_single' }}"
        sequence: !input single_2

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_single' }}"
        sequence: !input single_3

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_single' }}"
        sequence: !input single_4

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_double' }}"
        sequence: !input double_1

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_double' }}"
        sequence: !input double_2

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_double' }}"
        sequence: !input double_3

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_double' }}"
        sequence: !input double_4

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '1_hold' }}"
        sequence: !input hold_1

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '2_hold' }}"
        sequence: !input hold_2

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '3_hold' }}"
        sequence: !input hold_3

      - conditions:
          - condition: template
            value_template: "{{ trigger.payload == '4_hold' }}"
        sequence: !input hold_4

mode: single