blueprint:
  name: Moes/Tuya 4-Button Scene Switch (TS0044) - ZHA
  description: >
    Controls various entities based on single, double, and long press actions from a Moes 4-Button Scene Switch using ZHA.
  domain: automation

  input:
    switch_device:
      name: Zigbee Device
      description: Select the Moes/Tuya 4-Button Scene Switch.
      selector:
        device:
          integration: zha

    single_1:
      name: Action for 1 Single Press
      selector:
        action: {}
    single_2:
      name: Action for 2 Single Press
      selector:
        action: {}
    single_3:
      name: Action for 3 Single Press
      selector:
        action: {}
    single_4:
      name: Action for 4 Single Press
      selector:
        action: {}

    # Optional actions (remove requirement)
    double_1:
      name: Action for 1 Double Press
      selector:
        action: {}
      default: []
    double_2:
      name: Action for 2 Double Press
      selector:
        action: {}
      default: []
    
    hold_1:
      name: Action for 1 Hold Press
      selector:
        action: {}
      default: []
    hold_2:
      name: Action for 2 Hold Press
      selector:
        action: {}
      default: []

trigger:
  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_1
    id: button_1_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_2
    id: button_2_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_3
    id: button_3_single

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_short_press
    subtype: button_4
    id: button_4_single

  # Optional triggers (won't break if not used)
  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_double_press
    subtype: button_1
    id: button_1_double

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_double_press
    subtype: button_2
    id: button_2_double

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_long_press
    subtype: button_1
    id: button_1_hold

  - platform: device
    device_id: !input switch_device
    domain: zha
    type: remote_button_long_press
    subtype: button_2
    id: button_2_hold

action:
  - choose:
      - conditions:
          - condition: trigger
            id: button_1_single
        sequence: !input single_1

      - conditions:
          - condition: trigger
            id: button_2_single
        sequence: !input single_2

      - conditions:
          - condition: trigger
            id: button_3_single
        sequence: !input single_3

      - conditions:
          - condition: trigger
            id: button_4_single
        sequence: !input single_4

      # Optional actions (will be ignored if no input provided)
      - conditions:
          - condition: trigger
            id: button_1_double
        sequence: !input double_1

      - conditions:
          - condition: trigger
            id: button_2_double
        sequence: !input double_2

      - conditions:
          - condition: trigger
            id: button_1_hold
        sequence: !input hold_1

      - conditions:
          - condition: trigger
            id: button_2_hold
        sequence: !input hold_2

mode: restart